server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        health:
          enabled: true
        git:
          uri: https://github.com/Kolman-Freecss/CONFIG-Spring-Microservices-Gateway
          basedir: GATEWAY-SERVICE
          default-label: master